import img from "./images/sakil.jpg";
export const dummyUserRows = [
  {
    id: 1,
    firstName: "Sakil ",
    lastName: "Jomadder",
    username: "sakiljomadder",
    email: "sakiljomadder@mail.com",
    status: "active",
    avatar: img,
  },
  {
    id: 2,
    firstName: "Rasel",
    lastName: "Jomadder",
    username: "raseljomadder",
    email: "raseljomadder@mail.com",
    status: "inactive",
    avatar: img,
  },
  {
    id: 3,
    firstName: "Monir",
    lastName: "Jomadder",
    username: "monirjomadder",
    email: "monirjomadder@mail.com",
    status: "pending",
    avatar: img,
  },
  {
    id: 4,
    firstName: "Jolil",
    lastName: "Jomadder",
    username: "joliljomadder",
    email: "joliljomadder@mail.com",
    status: "active",
    avatar: img,
  },
  {
    id: 5,
    firstName: "Kobir",
    lastName: "Jomaddder",
    username: "kobirjomadder",
    email: "kobirjomadder@mail.com",
    status: "pending",
    avatar: img,
  },
  {
    id: 6,
    firstName: "Jahangir",
    lastName: "Jomadder",
    username: "jahangirjomadder",
    email: "jahangirjomadder@mail.com",
    status: "pending",
    avatar: img,
  },
  {
    id: 7,
    firstName: "Babu",
    lastName: "Jomadder",
    username: "babujomadder",
    email: "babujomadder@mail.com",
    status: "inactive",
    avatar: img,
  },
  {
    id: 8,
    firstName: "Liza",
    lastName: "Jomadder",
    username: "lizajomadder",
    email: "lizajomadder@mail.com",
    status: "active",
    avatar: img,
  },
  {
    id: 9,
    firstName: "Alamgir",
    lastName: "Jomadder",
    username: "alamgirjomadder",
    email: "alamgirjomadder@mail.com",
    status: "inactive",
    avatar: img,
  },
  {
    id: 10,
    firstName: "Emraj",
    lastName: "Jomadder",
    username: "emrajjomadder",
    email: "emrajjomadder@mail.com",
    status: "pending",
    avatar: img,
  },
  {
    id: 11,
    firstName: "Moon",
    lastName: "Jomadder",
    username: "moonjjomadder",
    email: "moonjomadder@mail.com",
    status: "active",
    avatar: img,
  },
];
