import img from "./images/sakil.jpg";
export const dummyUserRows = [
  {
    id: 1,
    firstName: "Sakil ",
    lastName: "Jomadder",
    username: "sakiljomadder",
    email: "sakiljomadder@mail.com",
    status: "active",
    avatar: img,
    mobileNo: "+8801720092787",
    designation: "Software Engineer",
  },
  {
    id: 2,
    firstName: "Rasel",
    lastName: "Jomadder",
    username: "raseljomadder",
    email: "raseljomadder@mail.com",
    status: "inactive",
    avatar: img,
    mobileNo: "+8801720092789",
    designation: "Ruby Engineer",
  },
  {
    id: 3,
    firstName: "Monir",
    lastName: "Jomadder",
    username: "monirjomadder",
    email: "monirjomadder@mail.com",
    status: "pending",
    avatar: img,
    mobileNo: "+8801720092781",
    designation: "Angular Engineer",
  },
  {
    id: 4,
    firstName: "Jolil",
    lastName: "Jomadder",
    username: "joliljomadder",
    email: "joliljomadder@mail.com",
    status: "active",
    avatar: img,
    mobileNo: "+8801720092782",
    designation: "React Engineer",
  },
  {
    id: 5,
    firstName: "Kobir",
    lastName: "Jomaddder",
    username: "kobirjomadder",
    email: "kobirjomadder@mail.com",
    status: "pending",
    avatar: img,
    mobileNo: "+8801720092783",
    designation: "Javascript Engineer",
  },
  {
    id: 6,
    firstName: "Jahangir",
    lastName: "Jomadder",
    username: "jahangirjomadder",
    email: "jahangirjomadder@mail.com",
    status: "pending",
    avatar: img,
    mobileNo: "+8801720092784",
    designation: "Dino Engineer",
  },
  {
    id: 7,
    firstName: "Babu",
    lastName: "Jomadder",
    username: "babujomadder",
    email: "babujomadder@mail.com",
    status: "inactive",
    avatar: img,
    mobileNo: "+8801720092785",
    designation: "Java Engineer",
  },
  {
    id: 8,
    firstName: "Liza",
    lastName: "Jomadder",
    username: "lizajomadder",
    email: "lizajomadder@mail.com",
    status: "active",
    avatar: img,
    mobileNo: "+8801720092786",
    designation: "Python Engineer",
  },
  {
    id: 9,
    firstName: "Alamgir",
    lastName: "Jomadder",
    username: "alamgirjomadder",
    email: "alamgirjomadder@mail.com",
    status: "inactive",
    avatar: img,
    mobileNo: "+8801720092788",
    designation: "React.js Engineer",
  },
  {
    id: 10,
    firstName: "Emraj",
    lastName: "Jomadder",
    username: "emrajjomadder",
    email: "emrajjomadder@mail.com",
    status: "pending",
    avatar: img,
    mobileNo: "+8801720092780",
    designation: "Node.js Engineer",
  },
  {
    id: 11,
    firstName: "Moon",
    lastName: "Jomadder",
    username: "moonjjomadder",
    email: "moonjomadder@mail.com",
    status: "active",
    avatar: img,
    mobileNo: "+8801720092787",
    designation: "PHP Engineer",
  },
];
